### PR TITLE
feat: navbar activities

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Created Activities screen.

### CODE REVIEW

**Review by MartaInes — CHANGES_REQUESTED** [review]
The screens are not finished. You have a good starting point, but there's still work to do. Try to add information in the different Activities screens.

**Comment by FranciscoRossoR** [comment]
- Added the remaining screens
    - Camps
    - Coexistence Room
    - Family Workshops
    - Open Room
    - Summer Club
- Added css style for said screens
- Capitalized names of all screens
- Fixed typo in "Coexistence" name (previously "Coexistance")

**Review by MartaInes — CHANGES_REQUESTED** [review]
Good job, we have all the requested screens. However, there are a few changes that could be done to improve it:
- Center the hover in the list of Activities in the main Activities page
- There is a misspelling in the tab "Talleres familiares", it says "poyo" instead of "apoyo"

**Comment by FranciscoRossoR** [comment]
- Fixed typo in FamilyWorkshops
- Fixed the hover offcenter in Activities by turning it into a table structure

**Review by MartaInes — CHANGES_REQUESTED** [review]
Good job fixing what I told you in the previous review, but I realized that the hover is bigger than the text and when you click on it (the part outside the text), it doesn't take you to the page, so it can be a bit confussing to the users. It would be better if it worked by clicking in any part of it.

**Comment by FranciscoRossoR** [comment]
Spread the link to the whole cells.

**Review by MartaInes — APPROVED** [review]
Great job!!

**Comment by fracalrod3** [comment]
Please resolve conflicts before I can proceed to review

**Comment by fracalrod3** [comment]
Seems alright for now

**Review by fracalrod3 — APPROVED** [review]
Seems alright for now

**Pull request merged**
